#pragma once
// ------------------------------------------------------------------------------

#include "stdafx.h"
#include "Protocol.h"
// ------------------------------------------------------------------------------

#define WIN_DRAW_CORD(x)		 ( ( pWinWidth * x ) / 640 )
#define WIN_DRAW_CORDY(x)		 ( ( pWinHeight * x ) / 480 )

#define FULL_X_IN_GAME_X(x)		( (640 * x) / pWinWidth)
#define FULL_Y_IN_GAME_Y(x)		( (480 * x) / pWinHeight)
// ------------------------------------------------------------------------------
//#if(USER_BUFF_ICON_EX==TRUE)

#define MAX_BUFF_INDEX	255//170
#define MAX_STATE_COUNT	 16
// ------------------------------------------------------------------------------

#define ADD_OPTION_SPEED					1
#define ADD_OPTION_ATTACK_DAMAGE			2
#define ADD_OPTION_DEFENSE					3
#define ADD_OPTION_LIFE						4
#define ADD_OPTION_MANA						5
#define ADD_OPTION_EXPERIENCE				6
#define ADD_OPTION_DROP_RATE				7
#define ADD_OPTION_SUSTENANCE				8
#define ADD_OPTION_STRENGTH					9
#define ADD_OPTION_DEXTERITY				10
#define ADD_OPTION_VITALITY					11
#define ADD_OPTION_ENERGY					12
#define ADD_OPTION_LEADERSHIP				13
#define ADD_OPTION_WRATH					14
#define ADD_OPTION_WIZARDRY					15
#define ADD_OPTION_MOBILITY					16
#define ADD_OPTION_WIZARD_DEFENSE			21
#define ADD_OPTION_MAGIC_DEFENSE			22
#define ADD_OPTION_REDUCE_DEFENSE			23
#define ADD_OPTION_REFLECT					24
#define ADD_OPTION_ATTACK_RATE				26
#define ADD_OPTION_WIZARD_DEFENSE_DURATION	28
#define ADD_OPTION_BERSERKMANA				31
#define ADD_OPTION_BERSERKLIFE				32
#define ADD_OPTION_MAGICDAMAGEMIN			33
#define ADD_OPTION_MAGICDAMAGEMAX			34
#define ADD_OPTION_ATTACK_NORMAL_DAMAGE		51
#define ADD_OPTION_MONSTER_DAMAGE_ABSORB	52
#define ADD_OPTION_LIFE_AUTO_RECOVERY		53
#define ADD_OPTION_MANA_AUTO_RECOVERY		54
#define ADD_OPTION_CRITICAL_DAMAGE			55
#define ADD_OPTION_EXCELLENT_DAMAGE			56
#define ADD_OPTION_XMASATTACK				57
#define ADD_OPTION_XMASDEFENSE				58
#define ADD_OPTION_LEVEL_BP					66
#define ADD_OPTION_LEVEL_SD					67
#define ADD_OPTION_BP						71
#define ADD_OPTION_SD						70
#define ADD_OPTION_IGNOREDEFENSE			72
#define ADD_OPTION_VITALITY_MONK			ADD_OPTION_VITALITY	//73 in original
#define ADD_OPTION_SUCCESSFULBLOCKING		74
#define SUB_OPTION_SUCCESSFULBLOCKING		75

#define ADD_OPTION_BERSAKER_DEFENCE			100
#define ADD_OPTION_BERSAKER_DAMAGE			101
// ------------------------------------------------------------------------------

enum eBuffID
{
	eAddExp		 = 1,
	eAddDamage	 = 2,
	eAddDefence  = 3,
	eAddBattle   = 4,
	eAddDrop     = 5,
	eAddDouble   = 6,
};
// -------------------------------------------------------------------------------

struct PMSG_SEND_BUFF_ICON_EX
{
	PSBMSG_HEAD h;
	BYTE btEffectIndex;
	char szBuffName[20];
	BYTE btEffectType[5]; 
	int iValue[5];
};

struct PMSG_SEND_BUFF_ICON
{
	PBMSG_HEAD h;	// C1:2D
	WORD wOptionType;
	WORD wEffectType;
	BYTE byEffectOption;
	int iLeftTime;
	BYTE btEffectIndex;
};
// ------------------------------------------------------------------------------

struct BUFF_DATA
{
	BYTE Index;
	char Name[50];
	char Text[200];
};
// ------------------------------------------------------------------------------

struct BUFF_USER
{
	int Index;
	int Time;
	int MaxTime;
};
// ------------------------------------------------------------------------------

enum eBuffEffectType
{
	AT_NULL_BUFF_EFFECT = 0,
	AT_INCREASE_ATTACK = 1,
	AT_INCREASE_DEFENSE = 2,
	AT_NPC_HELP = 3,
	AT_WIZARD_DEFENSE = 4,
	AT_INCREASE_CRITICAL_DMG = 5,
	AT_INFINITY_ARROW = 6,
	AT_INCREASE_AG_SPEED = 7,
	AT_SWELL_LIFE = 8,
	AT_SWELL_MANA = 9,
	AT_POTION_OF_BLESS = 10,
	AT_POTION_OF_SOUL = 11,
	AT_CANCEL_MAGIC = 12,
	AT_CASTLE_GATE_STATUS = 13,
	AT_WATCHING_TOWER = 14,
	AT_ATTACKING_GUILD1 = 15,
	AT_ATTACKING_GUILD2 = 16,
	AT_ATTACKING_GUILD3 = 17,
	AT_INVISIBILITY = 18,
	AT_DARK_ROD_SKILL = 19,
	AT_CASTLE_CROWN_STATUS = 20,
	AT_CW_ALTAR_ACTIVE = 21,
	AT_CW_ALTAR_INACTIVE = 22,
	AT_CW_ALTAR_STATUS = 23,
	AT_CW_ALTAR_ATTEMPT = 24,
	AT_CW_ALTAR_ATTACKING_STATUS = 25,
	AT_CW_ALTAR_HERO_STATUS = 26,
	AT_CW_NPC_TRANSPARENCY = 27,
	AT_GAMEMASTER_LOGO = 28,
	AT_PCBANG_SEAL_OF_ASCENSION = 29,
	AT_PCBANG_SEAL_OF_WEALTH = 30,
	AT_PCBANG_SEAL_OF_SUSTENANCE = 31,
	AT_ILLUSION_SPELL1 = 32,
	AT_ILLUSION_SPELL2 = 33,
	AT_ILLUSION_SHIELD_SPELL = 34,
	AT_HALLOWEEN_BLESSING = 35,
	AT_HALLOWEEN_RAGE = 36,
	AT_HALLOWEEN_SCREAM = 37,
	AT_HALLOWEEN_FOOD = 38,
	AT_HALLOWEEN_DRINK = 39,
	AT_CSHOP_SEAL_OF_ASCENSION = 40,
	AT_CSHOP_SEAL_OF_WEALTH = 41,
	AT_CSHOP_SEAL_OF_SUSTENANCE = 42,
	AT_CSHOP_SEAL_OF_MOBILITY = 43,
	AT_CSHOP_SCROLL_OF_QUICKNESS = 44,
	AT_CSHOP_SCROLL_OF_DEFENSE = 45,
	AT_CSHOP_SCROLL_OF_WRATH = 46,
	AT_CSHOP_SCROLL_OF_WIZARDRY = 47,
	AT_CSHOP_SCROLL_OF_HEALTH = 48,
	AT_CSHOP_SCROLL_OF_MANA = 49,
	AT_CSHOP_LEAP_OF_STRENGTH = 50,
	AT_CSHOP_LEAP_OF_QUICKNESS = 51,
	AT_CSHOP_LEAP_OF_HEALTH = 52,
	AT_CSHOP_LEAP_OF_ENERGY = 53,
	AT_CSHOP_LEAP_OF_CONTROL = 54,
	AT_POISON = 55,
	AT_ICE = 56,
	AT_ICE_ARROW = 57,
	AT_REDUCE_DEFENSE = 58,
	AT_REDUCE_ATTACK = 59,
	AT_REDUCE_MAGIC = 60,
	AT_STUN = 61,
	AT_MAGIC_DEFENSE = 62,
	AT_IMMUNE_MAGIC = 63,
	AT_IMMUNE_HARM = 64,
	AT_ILLUSION_RESTRICTION_SPELL = 65,
	AT_CRYWOLF_PROTECTION1 = 66,
	AT_CRYWOLF_PROTECTION2 = 67,
	AT_CRYWOLF_PROTECTION3 = 68,
	AT_CRYWOLF_PROTECTION4 = 69,
	AT_CRYWOLF_PROTECTION5 = 70,
	AT_DAMAGE_REFLECTION = 71,
	AT_SLEEP = 72,
	AT_BLIND = 73,
	AT_REQUIEM = 74,
	AT_EXPLOSION = 75,
	AT_WEAKNESS = 76,
	AT_INNOVATION = 77,
	AT_CHERRYBLOSSOM_STAMEN = 78,
	AT_CHERRYBLOSSOM_RICECAKE = 79,
	AT_CHERRYBLOSSOM_FLOWERPETAL = 80,
	AT_BERSERKER = 81,
	AT_EXPANSION_WIZARDRY = 82,
	AT_FLAME_STRIKE = 83,
	AT_GIGANTIC_STORM = 84,
	AT_LIGHTNING_SHOCK = 85,
	AT_DESTRUCTION = 86,
	AT_CSHOP_SEAL_OF_HEALING = 87,
	AT_CSHOP_SEAL_OF_DIVINITY = 88,
	AT_CSHOP_SCROLL_OF_BATTLE = 89,
	AT_CSHOP_SCROLL_OF_STRENGTHENER = 90,
	AT_XMASS_REWARD = 91,
	AT_XMASS_HEALTH = 92,
	AT_XMASS_MANA = 93,
	AT_XMASS_ATTACK = 94,
	AT_XMASS_DEFENSE = 95,
	AT_XMASS_DEXTERITY = 96,
	AT_XMASS_AG_RECOVERY = 97,
	AT_NEWPVPSYSTEM_WATCH_DUEL = 98,
	AT_CSHOP_GUARDIAN_AMULET = 99,
	AT_CSHOP_PROTECT_AMULET = 100,
	AT_CSHOP_MASTER_SEAL_OF_ASCENSION = 101,
	AT_CSHOP_MASTER_SEAL_OF_WEALTH = 102,
	AT_NEWPVPSYSTEM_REWARD = 103,
	AT_PCBANG_SEAL_OF_BALANCE = 104,
	AT_PARTY_EXP_BONUS = 112,
	AT_CSHOP_AG_BOOST = 113,
	AT_CSHOP_SD_BOOST = 114,
	AT_RFVITALITY = 130,
	AT_VIP_SILVER = 171,
	AT_VIP_GOLD = 172,
	AT_VIP_PLATINUM = 173,
	AT_PARTY_EXP_BONUS_EX = 174,
	AT_GUILD_BUFF = 175,
	AT_NPC_BUFF_EXP = 176,
	AT_NPC_BUFF_DAMAGE = 177,
	AT_NPC_BUFF_DEFENCE = 178,
	AT_NPC_BUFF_EXL_CRIT = 179,
	AT_NPC_BUFF_DROP = 180,
	AT_NPC_BUFF_DOUBLE = 181,
	AT_NOOB_BUFF = 182,
	AT_QUEST_BUFF = 183,
};

enum
{
	BUFF_ADD_ATTACK				=	1,
	BUFF_ADD_DEFENSE			=	2,
	BUFF_NPC_PHANTOM			=	3,
	BUFF_MANASHIELD				=	4,
	BUFF_ADD_CRITDMG			=	5,
	BUFF_INFINITY_ARROW			=	6,
	BUFF_AG_RECOVERYSPEED		=	7,
	BUFF_SWELL_LIFE				=	8,
	BUFF_SWELL_MANA				=	9,
	BUFF_POT_BLESS				=	10,
	BUFF_POT_SOUL				=	11,
	BUFF_REMOVEMAGIC			=	12,
	BUFF_GATESTATUS				=	13,
	BUFF_WATCHTOWER				=	14,
	BUFF_SIEGEGUILD1			=	15,
	BUFF_SIEGEGUILD2			=	16,
	BUFF_SIEGEGUILD3			=	17,
	BUFF_INVISIBILITY			=	18,
	BUFF_BATTLEROD				=	19,
	BUFF_CROWNREGISTER			=	20,
	BUFF_ALTAR_STATUS1			=	21,
	BUFF_ALTAR_STATUS2			=	22,
	BUFF_ALTAR_STATUS3			=	23,
	BUFF_ALTAR_STATUS4			=	24,
	BUFF_ALTAR_STATUS5			=	25,
	BUFF_ALTAR_STATUS6			=	26,
	BUFF_CRYWOLF_TRANSPARENCY	=	27,
	BUFF_GM						=	28,
	BUFF_SEAL_ASCENSION			=	29,
	BUFF_SEAL_WEALTH			=	30,
	BUFF_SEAL_SUSTENANCE		=	31,
	BUFF_IT_QUICKNESS			=	32,
	BUFF_IT_SUBLIMATION			=	33,
	BUFF_IT_PROTECTION			=	34,
	BUFF_JACK_BLESSING			=	35,
	BUFF_JACK_WRATH				=	36,
	BUFF_JACK_CRY				=	37,
	BUFF_JACK_FOOD				=	38,
	BUFF_JACK_DRINK				=	39,
	BUFF_SEAL_ASCENSION2		=	40,
	BUFF_SEAL_WEALTH2			=	41,
	BUFF_SEAL_SUSTENANCE2		=	42,
	BUFF_SEAL_MOBILITY			=	43,
	BUFF_SCROLL_QUICKNESS		=	44,
	BUFF_SCROLL_DEFENSE			=	45,
	BUFF_SCROLL_WRATH			=	46,
	BUFF_SCROLL_WIZARDRY		=	47,
	BUFF_SCROLL_HEALTH			=	48,
	BUFF_SCROLL_MANA			=	49,
	BUFF_ELIXIR_STR				=	50,
	BUFF_ELIXIR_DEX				=	51,
	BUFF_ELIXIR_VIT				=	52,
	BUFF_ELIXIR_ENE				=	53,
	BUFF_ELIXIR_COM				=	54,
	BUFF_POISON					=	55,
	BUFF_ICE					=	56,
	BUFF_ICEARROW				=	57,
	BUFF_DEFENSEDOWN			=	58,
	BUFF_ATTACKDOWN				=	59,
	BUFF_WIZARDRYDOWN			=	60,
	BUFF_STUN					=	61,
	BUFF_MAGICDEFENSE			=	62,
	BUFF_MONSTERMAGIC_RESIST	=	63,
	BUFF_MONCHEMISTRY_RESIST	=	64,
	BUFF_RESTRICTION			=	65,
	BUFF_CRYWOLF_STATUS1		=	66,
	BUFF_CRYWOLF_STATUS2		=	67,
	BUFF_CRYWOLF_STATUS3		=	68,
	BUFF_CRYWOLF_STATUS4		=	69,
	BUFF_CRYWOLF_STATUS5		=	70,
	BUFF_DAMAGEREFLECT			=	71,
	BUFF_SLEEP					=	72,
	BUFF_BLIND					=	73,
	BUFF_REQUIEM				=	74,
	BUFF_EXPLOSION				=	75,
	BUFF_WEAKNESS				=	76,
	BUFF_INNOVATION				=	77,
	BUFF_CHERRY_WINE			=	78,
	BUFF_CHERRY_RICECAKE		=	79,
	BUFF_CHERRY_FLOWERPETAL		=	80,
	BUFF_BERSERKER				=	81,
	BUFF_EXP_WIZARDRY			=	82,
	BUFF_FLAMESTRIKE			=	83,
	BUFF_GIGANTSTORM			=	84,
	BUFF_LIGHTNINGSHOCK			=	85,
	BUFF_COLD					=	86,
	BUFF_SEAL_HEALING			=	87,
	BUFF_SEAL_DIVINITY			=	88,
	BUFF_SCROLL_BATTLE			=	89,
	BUFF_SCROLL_STRENGTH		=	90,
	BUFF_SANTA_CHRISTMAS		=	91,
	BUFF_SANTA_HEALING			=	92,
	BUFF_SANTA_PROTECTION		=	93,
	BUFF_SANTA_STRENGHTHENER	=	94,
	BUFF_SANTA_DEFENSE			=	95,
	BUFF_SANTA_QUICKNESS		=	96,
	BUFF_SANTA_FORTUNE			=	97,
	BUFF_WATCH					=	98,
	BUFF_TALISMAN_GUARDIAN		=	99,
	BUFF_TALISMAN_ITEMPROTECT	=	100,
	BUFF_SEAL_ASCENSIONM		=	101,
	BUFF_SEAL_WEALTHM			=	102,
	BUFF_GLADIATOR_HONOR		=	103,
	BUFF_SEAL_STRENGTH			=	104,
	BUFF_ASCENSION				=	105,
	BUFF_PK_PENALTY				=	106,
	BUFF_PENALTY				=	107,
	BUFF_PENALTY2				=	108,
	BUFF_PARTYEXP				=	112,
	BUFF_MAXAG					=	113,
	BUFF_MAXSD					=	114,
	BUFF_VITALITY_MINIMUM		=	115,
	BUFF_VITALITY_LOW			=	116,
	BUFF_VITALITY_MEDIUM		=	117,
	BUFF_VITALITY_HIGH			=	118,
	BUFF_SEAL_WEALTH3			=	119,
	BUFF_BAN					=	120,
	BUFF_SCROLL_HEALING			=	121,
	BUFF_IGNORE_DEFENSE			=	129,
	BUFF_INCREASE_VIT			=	130,
	BUFF_INCREASE_DEFRATE		=	131,
	BUFF_DECREASE_DEFRATE		=	132,
	BUFF_INVINCIBILITY			=	133,
	BUFF_IRONDEFENSE			=	134,
	BUFF_SWELL_LIFE2			=	135,
	BUFF_SWELL_LIFE3			=	136,
	BUFF_BLEEDING				=	137,
	BUFF_EXP_WIZARDRY2			=	138,
	BUFF_EXP_WIZARDRY3			=	139,
	BUFF_MANASHIELD2			=	140,
	BUFF_DECREASE_ATTACKSPEED	=	141,
	BUFF_BLESS					=	142,
	BUFF_INFINITY_ARROW2		=	143,
	BUFF_BLIND2					=	144,
	BUFF_VAMPIRIC				=	145,
	BUFF_FREEZE					=	146,
	BUFF_EARTHBINDS				=	147,
	BUFF_ADD_CRITDMG2			=	148,
	BUFF_ADD_CRITDMG3			=	149,
	BUFF_BERSERKER2				=	150,
	BUFF_BERSERKER3				=	151,
	BUFF_BERSERKER4				=	152,
	BUFF_INCREASE_DEFRATE2		=	153,
	BUFF_INCREASE_DEFRATE3		=	154,
	BUFF_INCREASE_VIT2			=	155,
	BUFF_IGNORE_DEFENSE2		=	156,
	BUFF_FIRE					=	157,
	BUFF_FROST					=	158,
	BUFF__POISON				=	159,
	BUFF__POISON2				=	160,
	BUFF_BLESS2					=	161,
	BUFF_WEAKNESS2				=	162,
	BUFF_INNOVATION2			=	163,
	BUFF_DECREASE_DEFRATE2		=	164,
	BUFF_IRONDEFENSE2			=	165,
	BUFF_BLOODHOWL				=	166,
	BUFF_BLOODHOWL2				=	167,
	BUFF_PENETRATE_ARMOR		=	169,
	BUFF_FIRE2					=	174,
	BUFF_FROST2					=	175,
	BUFF_TORNADO				=	176,
	BUFF_BIND					=	177,
	BUFF_DARKNESS				=	178,
	BUFF_FIRETOWER				=	179,
	BUFF_WATERTOWER				=	180,
	BUFF_EARTHTOWER				=	181,
	BUFF_WINDTOWER				=	182,
	BUFF_DARKNESSTOWER			=	183,
	BUFF_RESURRECT_PENALTY		=	184,
	BUFF_EXP_VAULT				=	185,
	BUFF_CONFUSION				=	186,
	BUFF_EXPREWARD				=	187,
};

enum eEffectNumber
{
	EFFECT_GREATER_DAMAGE = 1,
	EFFECT_GREATER_DEFENSE = 2,
	EFFECT_ELF_BUFFER = 3,
	EFFECT_MANA_SHIELD = 4,
	EFFECT_GREATER_CRITICAL_DAMAGE = 5,
	EFFECT_INFINITY_ARROW = 6,
	EFFECT_BP_RECOVERY = 7,
	EFFECT_GREATER_LIFE = 8,
	EFFECT_GREATER_MANA = 9,
	EFFECT_BLESS_POTION = 10,
	EFFECT_SOUL_POTION = 11,
	EFFECT_DISABLE_MAGIC = 12,
	EFFECT_CASTLE_GATE_STATE = 13,
	EFFECT_GUILD_STATE1 = 14,
	EFFECT_GUILD_STATE2 = 15,
	EFFECT_GUILD_STATE3 = 16,
	EFFECT_GUILD_STATE4 = 17,
	EFFECT_INVISIBILITY = 18,
	EFFECT_GUILD_STATE5 = 19,
	EFFECT_CASTLE_CROWN_STATE = 20,
	EFFECT_CRYWOLF_STATE1 = 21,
	EFFECT_CRYWOLF_STATE2 = 22,
	EFFECT_CRYWOLF_STATE3 = 23,
	EFFECT_CRYWOLF_STATE4 = 24,
	EFFECT_CRYWOLF_STATE5 = 25,
	EFFECT_CRYWOLF_STATE6 = 26,
	EFFECT_CRYWOLF_STATE7 = 27,
	EFFECT_GAME_MASTER = 28,
	EFFECT_SEAL_OF_ASCENSION1 = 29,
	EFFECT_SEAL_OF_WEALTH1 = 30,
	EFFECT_SEAL_OF_SUSTENANCE1 = 31,
	EFFECT_ORDER_OF_SPEED = 32,
	EFFECT_ORDER_OF_SUBLIMATION = 33,
	EFFECT_ORDER_OF_PROTECTION = 34,
	EFFECT_HALLOWEEN1 = 35,
	EFFECT_HALLOWEEN2 = 36,
	EFFECT_HALLOWEEN3 = 37,
	EFFECT_HALLOWEEN4 = 38,
	EFFECT_HALLOWEEN5 = 39,
	EFFECT_SEAL_OF_ASCENSION2 = 40,
	EFFECT_SEAL_OF_WEALTH2 = 41,
	EFFECT_SEAL_OF_SUSTENANCE2 = 42,
	EFFECT_SEAL_OF_MOVEMENT = 43,
	EFFECT_SCROLL_OF_QUICK = 44,
	EFFECT_SCROLL_OF_DEFENSE = 45,
	EFFECT_SCROLL_OF_DAMAGE = 46,
	EFFECT_SCROLL_OF_MAGIC_DAMAGE = 47,
	EFFECT_SCROLL_OF_LIFE = 48,
	EFFECT_SCROLL_OF_MANA = 49,
	EFFECT_ELIXIR_OF_STRENGTH = 50,
	EFFECT_ELIXIR_OF_DEXTERITY = 51,
	EFFECT_ELIXIR_OF_VITALITY = 52,
	EFFECT_ELIXIR_OF_ENERGY = 53,
	EFFECT_ELIXIR_OF_LEADERSHIP = 54,
	EFFECT_POISON = 55,
	EFFECT_ICE = 56,
	EFFECT_ICE_ARROW = 57,
	EFFECT_FIRE_SLASH = 58,
	EFFECT_PHYSI_DAMAGE_IMMUNITY = 59,
	EFFECT_MAGIC_DAMAGE_IMMUNITY = 60,
	EFFECT_STERN = 61,
	EFFECT_MAGIC_DEFENSE = 62,
	EFFECT_MONSTER_PHYSI_DAMAGE_IMMUNITY = 63,
	EFFECT_MONSTER_MAGIC_DAMAGE_IMMUNITY = 64,
	EFFECT_ORDER_OF_RESTRAINT = 65,
	EFFECT_CRYWOLF_STATE8 = 66,
	EFFECT_CRYWOLF_STATE9 = 67,
	EFFECT_CRYWOLF_STATE10 = 68,
	EFFECT_CRYWOLF_STATE11 = 69,
	EFFECT_CRYWOLF_STATE12 = 70,
	EFFECT_DAMAGE_REFLECT = 71,
	EFFECT_SLEEP = 72,
	EFFECT_BLIND = 73,
	EFFECT_NEIL = 74,
	EFFECT_SAHAMUTT = 75,
	EFFECT_LESSER_DAMAGE = 76,
	EFFECT_LESSER_DEFENSE = 77,
	EFFECT_CHERRY_BLOSSOM1 = 78,
	EFFECT_CHERRY_BLOSSOM2 = 79,
	EFFECT_CHERRY_BLOSSOM3 = 80,
	EFFECT_SWORD_POWER = 81,
	EFFECT_MAGIC_CIRCLE = 82,
	EFFECT_SWORD_SLASH = 83,
	EFFECT_LIGHTNING_STORM = 84,
	EFFECT_RED_STORM = 85,
	EFFECT_FROZEN_STAB = 86,
	EFFECT_SEAL_OF_LIFE = 87,
	EFFECT_SEAL_OF_MANA = 88,
	EFFECT_SCROLL_OF_BATTLE = 89,
	EFFECT_SCROLL_OF_STRENGTH = 90,
	EFFECT_CHRISTMAS1 = 91,
	EFFECT_CHRISTMAS2 = 92,
	EFFECT_CHRISTMAS3 = 93,
	EFFECT_CHRISTMAS4 = 94,
	EFFECT_CHRISTMAS5 = 95,
	EFFECT_CHRISTMAS6 = 96,
	EFFECT_CHRISTMAS7 = 97,
	EFFECT_DUEL_ARENA_WATCH = 98,
	EFFECT_TALISMAN_OF_GUARDIAN = 99,
	EFFECT_TALISMAN_OF_PROTECTION = 100,
	EFFECT_MASTER_SEAL_OF_ASCENSION = 101,
	EFFECT_MASTER_SEAL_OF_WEALTH = 102,
	EFFECT_GLADIATORS_GLORY = 103,
	EFFECT_DOUBLE_GOER_DELETE = 105,
	EFFECT_PARTY_EXPERIENCE_BONUS = 112,
	EFFECT_MAX_AG_BOOST_AURA = 113,
	EFFECT_MAX_SD_BOOST_AURA = 114,
	EFFECT_SCROLL_OF_HEALING = 121,
	EFFECT_HAWK_FIGURINE = 122,
	EFFECT_GOAT_FIGURINE = 123,
	EFFECT_OAK_CHARM = 124,
	EFFECT_MAPLE_CHARM = 125,
	EFFECT_GOLDEN_OAK_CHARM = 126,
	EFFECT_GOLDEN_MAPLE_CHARM = 127,
	EFFECT_WORN_HORSESHOE = 128,
	EFFECT_GREATER_IGNORE_DEFENSE_RATE = 129,
	EFFECT_FITNESS = 130,
	EFFECT_GREATER_DEFENSE_SUCCESS_RATE = 131,
	EFFECT_IRON_DEFENSE = 134,
	EFFECT_GREATER_LIFE_ENHANCED = 135,
	EFFECT_GREATER_LIFE_MASTERED = 136,
	EFFECT_DEATH_STAB_ENHANCED = 137,
	EFFECT_MAGIC_CIRCLE_IMPROVED = 138,
	EFFECT_MAGIC_CIRCLE_ENHANCED = 139,
	EFFECT_MANA_SHIELD_MASTERED = 140,
	EFFECT_FROZEN_STAB_MASTERED = 141,
	EFFECT_BLESS = 142,
	EFFECT_INFINITY_ARROW_IMPROVED = 143,
	EFFECT_BLIND_IMPROVED = 144,
	EFFECT_DRAIN_LIFE_ENHANCED = 145,
	EFFECT_ICE_STORM_ENHANCED = 146,
	EFFECT_EARTH_PRISON = 147,
	EFFECT_GREATER_CRITICAL_DAMAGE_MASTERED = 148,
	EFFECT_GREATER_CRITICAL_DAMAGE_EXTENDED = 149,
	EFFECT_SWORD_POWER_IMPROVED = 150,
	EFFECT_SWORD_POWER_ENHANCED = 151,
	EFFECT_SWORD_POWER_MASTERED = 152,
	EFFECT_GREATER_DEFENSE_SUCCESS_RATE_IMPROVED = 153,
	EFFECT_GREATER_DEFENSE_SUCCESS_RATE_ENHANCED = 154,
	EFFECT_FITNESS_IMPROVED = 155,
	EFFECT_DRAGON_ROAR_ENHANCED = 157,
	EFFECT_CHAIN_DRIVER_ENHANCED = 158,
	EFFECT_POISON_ARROW = 159,
	EFFECT_POISON_ARROW_IMPROVED = 160,
	EFFECT_BLESS_IMPROVED = 161,
	EFFECT_LESSER_DAMAGE_IMPROVED = 162,
	EFFECT_LESSER_DEFENSE_IMPROVED = 163,
	EFFECT_FIRE_SLASH_ENHANCED = 164,
	EFFECT_IRON_DEFENSE_IMPROVED = 165,
	EFFECT_BLOOD_HOWLING = 166,
	EFFECT_BLOOD_HOWLING_IMPROVED = 167,
	EFFECT_PENTAGRAM_JEWEL_HALF_SD = 174,
	EFFECT_PENTAGRAM_JEWEL_HALF_MP = 175,
	EFFECT_PENTAGRAM_JEWEL_HALF_SPEED = 176,
	EFFECT_PENTAGRAM_JEWEL_HALF_HP = 177,
	EFFECT_PENTAGRAM_JEWEL_STUN = 178,
	EFFECT_PENTAGRAM_JEWEL_SLOW = 186,
	EFFECT_TALISMAN_OF_ASCENSION1 = 190,
	EFFECT_TALISMAN_OF_ASCENSION2 = 191,
	EFFECT_TALISMAN_OF_ASCENSION3 = 192,
	EFFECT_SEAL_OF_ASCENSION3 = 193,
	EFFECT_MASTER_SEAL_OF_ASCENSION2 = 194,
	EFFECT_BLESSING_OF_LIGHT = 195,
	EFFECT_MASTER_SCROLL_OF_DEFENSE = 196,
	EFFECT_MASTER_SCROLL_OF_MAGIC_DAMAGE = 197,
	EFFECT_MASTER_SCROLL_OF_LIFE = 198,
	EFFECT_MASTER_SCROLL_OF_MANA = 199,
	EFFECT_MASTER_SCROLL_OF_DAMAGE = 200,
	EFFECT_MASTER_SCROLL_OF_HEALING = 201,
	EFFECT_MASTER_SCROLL_OF_BATTLE = 202,
	EFFECT_MASTER_SCROLL_OF_STRENGTH = 203,
	EFFECT_MASTER_SCROLL_OF_QUICK = 204,
};

#define sub_777CB0_Addr		((void(__fastcall*)(struct_v15 * This, int a2)) 0x777CB0)

struct struct_v15
{
  char gap0[16];
  int Pos_X;
  int Pos_Y;
};

class BuffIcon
{
public:
	BuffIcon();
	~BuffIcon();

	static void __fastcall GetCoord(struct_v15 * This, int a2);

	void Init();
	void Load();
	void BindIcon(BYTE Index,  char* Name, char* Text);

	void Draw(float StartX, float StartY);
	void DrawBuffInfo(int BuffIndex, int InfoIndex, float iX, float iY, int line);
	static unsigned int __stdcall Timer(void *Args);
	void Recv(PMSG_SEND_BUFF_ICON* DataRecv);

	void DeleteAllBuff();
	void DrawBuffInfoEx(int BuffIndex, float iX, float iY, int iTime);

	char* GetBuffName(int ID);
	char* GetAddedBuffName(int buff);

	void GC_BuffInfo(PMSG_SEND_BUFF_ICON_EX* aRecv);

	int LoadBuffCount;
	int UserBuffCount;

	HANDLE hThread;
	BUFF_DATA	DataBuff[MAX_BUFF_INDEX];
	BUFF_USER	UserBuff[MAX_STATE_COUNT];
};
extern BuffIcon g_BuffIcon;
// ------------------------------------------------------------------------------
//#endif